---
title: "Modeling"
author: "Shane Hauck"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load packages
```{r}
library(tidyverse)
library(glmnet)
library(Matrix)

```

# Load data
```{r}
full_df <- read_csv("cleaned_WorldCup_passes.csv")
```



# Square root timeInPoss
```{r}
full_df <- full_df %>%
  mutate(totalTimeInPoss_sqrt = sqrt(totalTimeInPoss))

```


# Columns for LASSO model
```{r}
rmv_cols <- c(
  "possession_team", "opposition_team", "player_id", "player_name", "position_id", "totalTimeInPoss"
)

lasso_df <- full_df %>%
  select(-all_of(rmv_cols)) %>% 
  select(id, totalTimeInPoss_sqrt, everything())

```

# Fit LASSO model to predict totalTimeInPoss_sqrt to extract important features
```{r}
set.seed(123)
lasso_model <- cv.glmnet(
  x = as.matrix(lasso_df %>% select(-id, -totalTimeInPoss_sqrt)),
  y = lasso_df$totalTimeInPoss_sqrt,
  alpha = 1,
  family = "gaussian",
  nfolds = 10
)

plot(lasso_model)

# Extract coefficients at lambda.min
coefficients <- coef(lasso_model, s = "lambda.min")

# Coerce to a regular matrix and check non-zero entries
coefficients_matrix <- as.matrix(coefficients)
non_zero_indices <- which(coefficients_matrix[,1] != 0)

# Extract names of non-zero coefficients
non_zero_coefficients <- rownames(coefficients_matrix)[non_zero_indices]

# Remove intercept
non_zero_coefficients <- non_zero_coefficients[-1]


```

# Fit model with training testing on RMSE with test
```{r}
set.seed(123)
train_idx <- sample(1:nrow(lasso_df), 0.8*nrow(lasso_df))
train_data <- lasso_df[train_idx,]
test_data <- lasso_df[-train_idx,]

x_train <- as.matrix(train_data %>% select(-id, -totalTimeInPoss_sqrt))
y_train <- train_data$totalTimeInPoss_sqrt
x_test <- as.matrix(test_data %>% select(-id, -totalTimeInPoss_sqrt))
y_test <- test_data$totalTimeInPoss_sqrt

# Fit LASSO model using cross-validation
lasso_model <- cv.glmnet(
  x = x_train,
  y = y_train,
  alpha = 1,
  family = "gaussian",
  nfolds = 10
)

# Plot the cross-validated LASSO model
plot(lasso_model)

# Predict on the test dataset using the lambda that gives minimum mean cross-validated error
predicted_values <- predict(lasso_model, s = "lambda.min", newx = x_test)

# Calculate RMSE
rmse <- sqrt(mean((y_test - predicted_values)^2))
print(paste("RMSE:", rmse))

# Plotting predicted vs observed values
obs_vs_pred <- data.frame(Observed = y_test, Predicted = as.vector(predicted_values))
ggplot(obs_vs_pred, aes(x = Predicted, y = Observed)) +
  geom_point(alpha = 0.25) +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Observed vs Predicted values",
       x = "Predicted",
       y = "Observed")

```






